version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
          VERSION: 1.0.0
    ports:
      - "4200:80"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - my-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
          VERSION: 1.0.0
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mydb
    restart: unless-stopped
    networks:
      - my-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - my-network

volumes:
  mongodb_data:

networks:
  my-network:
    driver: bridge